#ifndef FRACTALCASH_CONFIG_H
#define FRACTALCASH_CONFIG_H
#define FRACTALCASH_VERSION "0.1.0"
#define FRACTALCASH_NETWORK_PORT 18444
#define FRACTALCASH_MAGIC_BYTES 0xFAFBFCFD
#endif // FRACTALCASH_CONFIG_H
